<a href="https://colab.research.google.com/github/serereuk-tf/Tensorflow-Example/blob/main/Day2/tensorflow_vs_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow와 Pytorch간 모듈의 차이점 분석

## 1. Conv 모듈

* Pytorch와 Tensorflow의 가장 큰 차이점은 이미지 shape 순서!
    * Pytorch 같은 경우 BCWH의 형태이지만
    * Tensorflow의 경우에는 BWHC의 형태로 구축해줘야함

* input channel을 집어넣어야하는지에 대한 여부
    * Tensorflow는 input channel을 안 집어넣어도 됨 -> 다이나믹하게 계산 가능하고 `Input`레이어로 이후에 다 계산됨
    * 하지만 토치는 직접 정해줘야하는 단점이 있

* 또 다른 차이점은 Padding
    * Tensorflow 같은 경우 padding에 대해서 same을 통해 복잡한 계산 필요 X
    * 하지만 torch 같은 경우 연산 해줘야함!





In [1]:
import numpy as np

# Framework
import torch 
import tensorflow as tf

In [ ]:
np.random.seed(0)

ex_for_TF = np.random.rand(1, 15, 15, 3).astype(np.float32)

In [ ]:
conv_layer = tf.keras.layers.Conv2D(filters=1, kernel_size=3, padding='same')
print('tensorflow shape : {}'.format(conv_layer(ex_for_TF).shape))

tensorflow shape : (1, 15, 15, 1)


아래와 같이 shape를 변경해줘서 인풋으로 집어넣어주자!

In [ ]:
ex_for_torch = torch.tensor(ex_for_TF.reshape(1, 3, 15, 15))

conv_layer_torch = torch.nn.Conv2d(in_channels=3, out_channels=1,
                                   kernel_size=3, padding=1)

print('tensorflow shape : {}'.format(conv_layer_torch(ex_for_torch).shape))

tensorflow shape : torch.Size([1, 1, 15, 15])


## 2. MaxPool2D

* 역시 channel shape가 다름

* TF : pool_size Torch : kernel_size


In [5]:
ex_for_TF = np.arange(9).reshape(1, 3, 3, 1).astype(np.float32)

In [15]:
maxpool2d_layer = tf.keras.layers.MaxPool2D(pool_size=2, strides=1)
print(maxpool2d_layer(ex_for_TF).numpy())
print('tensorflow shape : {}'.format(maxpool2d_layer(ex_for_TF).shape))

[[[[4.]
   [5.]]

  [[7.]
   [8.]]]]
tensorflow shape : (1, 2, 2, 1)


In [16]:
ex_for_torch = torch.tensor(ex_for_TF.reshape(1, 1, 3, 3))

maxpool2d_layer_torch = torch.nn.MaxPool2d(kernel_size=2, stride=1)
print(maxpool2d_layer_torch(ex_for_torch))
print('tensorflow shape : {}'.format(maxpool2d_layer_torch(ex_for_torch).shape))

tensor([[[[4., 5.],
          [7., 8.]]]])
tensorflow shape : torch.Size([1, 1, 2, 2])


## 3. Batchnorm

In [ ]:
np.random.seed(0)

ex_for_TF = np.random.rand(1, 15, 15, 3).astype(np.float32)